<?php

namespace Database\Seeders;

use App\Models\Plant;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PlantSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $plants = [
            // ── Documento de referência ────────────────────────────────────────
            [
                'nome_popular'   => 'Flor-da-Fortuna',
                'nome_cientifico'=> 'Kalanchoe blossfeldiana',
                'familia'        => 'Crassulaceae',
                'genero'         => 'Kalanchoe',
                'especie'        => 'K. blossfeldiana',
                'origem'         => 'Madagascar',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 30,
                'toxica_pets'    => true,
                'epoca_poda'     => ['outono', 'inverno'],
                'beneficios'     => 'Planta ornamental resistente; flores duram semanas ou até meses. Precisa de pouca água e pouca manutenção — ótima para decorar interiores e varandas.',
                'maleficios'     => 'Tóxica para cães e gatos. Pode causar irritação gastrointestinal, salivação excessiva e vômito se ingerida por animais domésticos.',
                'curiosidades'   => 'Simboliza boa sorte e tem floração duradoura (até 3 meses). Suas cores variam entre vermelho, amarelo, branco e rosa.',
            ],
            [
                'nome_popular'   => 'Olho-de-Boneca',
                'nome_cientifico'=> 'Dendrobium nobile',
                'familia'        => 'Orchidaceae',
                'genero'         => 'Dendrobium',
                'especie'        => 'D. nobile',
                'origem'         => 'América Tropical',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 60,
                'toxica_pets'    => true,
                'epoca_poda'     => ['inverno', 'primavera'],
                'beneficios'     => 'Muito usada na decoração, flores bonitas e duradouras. Ajuda a deixar o ambiente mais agradável.',
                'maleficios'     => 'Pode causar leve irritação se ingerida, especialmente em pets. Pode desencadear alergia em algumas pessoas.',
                'curiosidades'   => 'O segredo para floração abundante é um período de dormência no outono/inverno: menos água, temperaturas noturnas mais baixas e muita luz.',
            ],
            [
                'nome_popular'   => 'Cambará',
                'nome_cientifico'=> 'Lantana camara',
                'familia'        => 'Verbenaceae',
                'genero'         => 'Lantana',
                'especie'        => 'L. camara',
                'origem'         => 'América Tropical',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 200,
                'toxica_pets'    => true,
                'epoca_poda'     => ['inverno', 'primavera'],
                'beneficios'     => 'Atrai polinizadores (borboletas e abelhas). Usada na medicina popular para problemas respiratórios, inflamações e febre.',
                'maleficios'     => 'Planta tóxica, principalmente os frutos verdes. Pode causar náusea, vômito, dor abdominal e problemas no fígado em casos graves.',
                'curiosidades'   => 'Muda a cor das flores durante o processo de maturação. Também conhecida como Lantana, Camará e Lantana-arbustiva.',
            ],
            [
                'nome_popular'   => 'Luca-manso',
                'nome_cientifico'=> 'Yucca filamentosa',
                'familia'        => 'Asparagaceae',
                'genero'         => 'Yucca',
                'especie'        => 'Y. filamentosa',
                'origem'         => 'América Central',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 200,
                'toxica_pets'    => true,
                'epoca_poda'     => ['primavera', 'verão'],
                'beneficios'     => 'Ação anti-inflamatória e antioxidante; auxilia na digestão e pode fortalecer o sistema imunológico. Uso ornamental marcante no paisagismo.',
                'maleficios'     => 'Pode ser tóxica se consumida de forma inadequada, causando náusea e irritação no estômago. Folhas pontiagudas podem causar cortes.',
                'curiosidades'   => 'Planta ornamental perene muito resistente, nativa de regiões áridas e semiáridas. Também chamada de Agulha-de-Adão.',
            ],
            [
                'nome_popular'   => 'Glória-da-Manhã',
                'nome_cientifico'=> 'Evolvulus glomeratus',
                'familia'        => 'Convolvulaceae',
                'genero'         => 'Evolvulus',
                'especie'        => 'E. glomeratus',
                'origem'         => 'Brasil',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 30,
                'toxica_pets'    => true,
                'epoca_poda'     => ['inverno', 'primavera'],
                'beneficios'     => 'Planta nativa com flores azuis vibrantes. Usada para cobrir cercas e pergolados; atrai abelhas e borboletas.',
                'maleficios'     => 'Pode ser tóxica se ingerida — sementes e folhas podem causar náusea, vômito e diarreia em pessoas e animais.',
                'curiosidades'   => 'Nativa do Brasil, também chamada de Azulzinha. Uma das poucas plantas com flores verdadeiramente azuis.',
            ],
            [
                'nome_popular'   => 'Maria-Pretinha',
                'nome_cientifico'=> 'Solanum americanum',
                'familia'        => 'Solanaceae',
                'genero'         => 'Solanum',
                'especie'        => 'S. americanum',
                'origem'         => 'Américas',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 100,
                'toxica_pets'    => true,
                'epoca_poda'     => [],
                'beneficios'     => 'Uso medicinal tradicional para inflamações, febre e problemas de pele. Possui compostos estudados na fitoterapia.',
                'maleficios'     => 'Frutos verdes e folhas cruas são tóxicos. Pode causar náusea, vômito e diarreia. Risco especial para crianças e animais.',
                'curiosidades'   => 'Também chamada de Pimenta-de-galinha. Seus frutos pretos maduros são menos tóxicos, mas o preparo inadequado é perigoso.',
            ],
            [
                'nome_popular'   => 'Imbé Burle Marx',
                'nome_cientifico'=> 'Philodendron Burle Marx',
                'familia'        => 'Araceae',
                'genero'         => 'Philodendron',
                'especie'        => 'P. Burle Marx',
                'origem'         => 'Brasil',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 400,
                'toxica_pets'    => true,
                'epoca_poda'     => ['primavera', 'verão'],
                'beneficios'     => 'Planta ornamental imponente, muito usada em jardins e interiores. Fácil de cuidar e adapta-se bem à meia-sombra.',
                'maleficios'     => 'Tóxica se ingerida (oxalato de cálcio): causa irritação na boca, garganta, inchaço e vômito. Seiva irrita a pele. Perigosa para pets.',
                'curiosidades'   => 'Recebeu o nome em homenagem ao paisagista Roberto Burle Marx. A espécie está em risco em seu habitat natural por causa do tráfico ilegal.',
            ],
            [
                'nome_popular'   => 'Lavanda-Francesa',
                'nome_cientifico'=> 'Lavandula dentata',
                'familia'        => 'Lamiaceae',
                'genero'         => 'Lavandula',
                'especie'        => 'L. dentata',
                'origem'         => 'Região do Mediterrâneo',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 100,
                'toxica_pets'    => false,
                'epoca_poda'     => ['primavera', 'verão', 'outono'],
                'beneficios'     => 'Relaxamento, melhora do sono, auxílio na digestão, ação antibacteriana e cuidado da pele. Também usada como repelente natural.',
                'maleficios'     => 'Pode causar alergias, irritação e sonolência excessiva se usada em excesso. Evitar contato direto com mucosas.',
                'curiosidades'   => 'A lavanda-francesa é mais tolerante ao calor e umidade do que outras espécies do gênero, o que a torna ideal para o clima brasileiro.',
            ],
            [
                'nome_popular'   => 'Croton',
                'nome_cientifico'=> 'Codiaeum variegatum',
                'familia'        => 'Euphorbiaceae',
                'genero'         => 'Codiaeum',
                'especie'        => 'C. variegatum',
                'origem'         => 'Sudeste Asiático',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 300,
                'toxica_pets'    => true,
                'epoca_poda'     => ['inverno', 'primavera'],
                'beneficios'     => 'Folhas multicoloridas e vibrantes tornam a planta um destaque em jardins e interiores. Fácil de cultivar em clima quente.',
                'maleficios'     => 'Tóxica se ingerida: causa náusea, vômito e diarreia. A seiva pode irritar a pele e os olhos.',
                'curiosidades'   => 'As cores das folhas intensificam com mais exposição ao sol. Pode apresentar vermelho, amarelo, laranja e verde na mesma folha.',
            ],
            [
                'nome_popular'   => 'Goiabeira',
                'nome_cientifico'=> 'Psidium guajava',
                'familia'        => 'Myrtaceae',
                'genero'         => 'Psidium',
                'especie'        => 'P. guajava',
                'origem'         => 'América Tropical',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 1000,
                'toxica_pets'    => false,
                'epoca_poda'     => ['inverno', 'primavera'],
                'beneficios'     => 'Frutos ricos em vitamina C, fibras e antioxidantes. As folhas têm propriedades medicinais reconhecidas para diarreia e inflamações.',
                'maleficios'     => 'Consumo excessivo pode causar prisão de ventre. Frutos verdes têm maior adstringência e podem causar desconforto intestinal.',
                'curiosidades'   => 'Seus frutos têm maior concentração de vitamina C do que a laranja. Nativa das Américas, é cultivada em todo o mundo tropical.',
            ],
            [
                'nome_popular'   => 'Alamanda-Roxa',
                'nome_cientifico'=> 'Allamanda blanchetii',
                'familia'        => 'Apocynaceae',
                'genero'         => 'Allamanda',
                'especie'        => 'A. blanchetii',
                'origem'         => 'Brasil',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 400,
                'toxica_pets'    => true,
                'epoca_poda'     => ['inverno', 'primavera'],
                'beneficios'     => 'Planta ornamental com flores roxas vistosas. Usada em cercas, muros e paisagismo. Floração intensa na primavera e verão.',
                'maleficios'     => 'Tóxica se ingerida: pode causar náusea, vômito e diarreia. A seiva leitosa pode causar irritação na pele e nos olhos.',
                'curiosidades'   => 'Nativa do Brasil e altamente rústica, com floração quase o ano todo em regiões tropicais. Nome em homenagem ao médico Friedrich Allaman.',
            ],
            [
                'nome_popular'   => 'Palmeira Areca',
                'nome_cientifico'=> 'Dypsis lutescens',
                'familia'        => 'Arecaceae',
                'genero'         => 'Dypsis',
                'especie'        => 'D. lutescens',
                'origem'         => 'Madagascar',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 1200,
                'toxica_pets'    => false,
                'epoca_poda'     => ['primavera', 'verão'],
                'beneficios'     => 'Excelente purificadora de ar em ambientes internos; umidifica o ambiente naturalmente e cria sensação de bem-estar tropical.',
                'maleficios'     => 'Pode causar alergias leves em pessoas sensíveis ao pólen. Deixa cair folhas secas com frequência.',
                'curiosidades'   => 'Está ameaçada de extinção em seu habitat natural em Madagascar. É uma das palmeiras mais vendidas no mundo para uso ornamental.',
            ],
            [
                'nome_popular'   => 'Coqueiro de Vênus',
                'nome_cientifico'=> 'Cordyline fruticosa',
                'familia'        => 'Asparagaceae',
                'genero'         => 'Cordyline',
                'especie'        => 'C. fruticosa',
                'origem'         => 'Filipinas',
                'habitat_luz'    => 'sol_pleno',
                'porte_max_cm'   => 800,
                'toxica_pets'    => true,
                'epoca_poda'     => ['primavera'],
                'beneficios'     => 'Planta ornamental fácil de cuidar, valoriza jardins e espaços abertos. Produz flores perfumadas com aroma adocicado.',
                'maleficios'     => 'Pode causar leve irritação ou desconforto em pessoas sensíveis. Não deve ser ingerida por pets.',
                'curiosidades'   => 'Associada ao misticismo e à sorte em várias culturas do Pacífico. Suas folhas variam do verde ao roxo-avermelhado conforme a cultivar.',
            ],
            [
                'nome_popular'   => 'Bambu da Sorte',
                'nome_cientifico'=> 'Dracaena sanderiana',
                'familia'        => 'Asparagaceae',
                'genero'         => 'Dracaena',
                'especie'        => 'D. sanderiana',
                'origem'         => 'Camarões',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 100,
                'toxica_pets'    => true,
                'epoca_poda'     => [],
                'beneficios'     => 'Planta decorativa fácil de cuidar, associada à prosperidade e energia positiva no Feng Shui.',
                'maleficios'     => 'Pode ser tóxica para cães e gatos se ingerida, causando vômito e salivação excessiva.',
                'curiosidades'   => 'Famoso por atrair prosperidade. Extremamente adaptável: cresce tanto em água quanto em terra. Não é um bambu de verdade.',
            ],
            [
                'nome_popular'   => 'Aperta-Ruão',
                'nome_cientifico'=> 'Piper aduncum',
                'familia'        => 'Piperaceae',
                'genero'         => 'Piper',
                'especie'        => 'P. aduncum',
                'origem'         => 'México e América Central',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 600,
                'toxica_pets'    => true,
                'epoca_poda'     => ['inverno'],
                'beneficios'     => 'Usada popularmente para inflamações e cicatrização. Possui propriedades medicinais e pode ser usada como tempero em algumas culturas.',
                'maleficios'     => 'Pode ser tóxica se ingerida em grande quantidade, causando vômito e diarreia. Não deve ser usada internamente sem orientação.',
                'curiosidades'   => 'Parente da pimenta-do-reino. Considerada espécie invasora em algumas regiões do mundo por seu crescimento rápido.',
            ],
            [
                'nome_popular'   => 'Palmeira de Leque',
                'nome_cientifico'=> 'Livistona chinensis',
                'familia'        => 'Arecaceae',
                'genero'         => 'Livistona',
                'especie'        => 'L. chinensis',
                'origem'         => 'Vanuatu',
                'habitat_luz'    => 'sombra',
                'porte_max_cm'   => 1500,
                'toxica_pets'    => false,
                'epoca_poda'     => ['primavera', 'verão'],
                'beneficios'     => 'Planta ornamental imponente que melhora a umidade do ambiente. Símbolo de longevidade em várias culturas asiáticas.',
                'maleficios'     => 'Pode causar alergias leves e pequenos cortes ao manusear suas folhas. Frutos não devem ser ingeridos.',
                'curiosidades'   => 'Suas folhas em formato de leque podem chegar a 1,5 m de diâmetro. Nativa do sul da China e Japão, apesar do nome de origem.',
            ],
            [
                'nome_popular'   => 'Espada de São Jorge',
                'nome_cientifico'=> 'Sansevieria trifasciata',
                'familia'        => 'Asparagaceae',
                'genero'         => 'Sansevieria',
                'especie'        => 'S. trifasciata',
                'origem'         => 'África Ocidental',
                'habitat_luz'    => 'sombra',
                'porte_max_cm'   => 100,
                'toxica_pets'    => true,
                'epoca_poda'     => [],
                'beneficios'     => 'Purificadora de ar reconhecida pela NASA. Converte CO₂ em oxigênio à noite. Símbolo de proteção e resistência.',
                'maleficios'     => 'Tóxica se ingerida por pets: causa salivação excessiva, náusea e vômito. Evitar contato das folhas com olhos.',
                'curiosidades'   => 'Uma das plantas mais resistentes do planeta: sobrevive semanas sem água e tolera ambientes com pouquíssima luz.',
            ],
            [
                'nome_popular'   => 'Peperômia-Filodendro',
                'nome_cientifico'=> 'Peperomia serpens',
                'familia'        => 'Piperaceae',
                'genero'         => 'Peperomia',
                'especie'        => 'P. serpens',
                'origem'         => 'América Central e do Sul',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 40,
                'toxica_pets'    => false,
                'epoca_poda'     => ['primavera'],
                'beneficios'     => 'Segura para pets e crianças. Planta decorativa compacta e fácil de cuidar. Adaptável a vários tipos de iluminação interna.',
                'maleficios'     => 'Consumo excessivo pode causar leve desconforto gástrico. Não apresenta toxicidade significativa.',
                'curiosidades'   => 'Comestível com sabor similar ao da pimenta-do-reino. Muito usada em terrários e jardins verticais pela sua forma rasteira.',
            ],
            [
                'nome_popular'   => 'Barba de Falcão',
                'nome_cientifico'=> 'Youngia japonica',
                'familia'        => 'Asteraceae',
                'genero'         => 'Youngia',
                'especie'        => 'Y. japonica',
                'origem'         => 'China',
                'habitat_luz'    => 'sombra',
                'porte_max_cm'   => 60,
                'toxica_pets'    => false,
                'epoca_poda'     => ['primavera', 'verão'],
                'beneficios'     => 'Pode auxiliar na digestão e tem ação anti-inflamatória. Folhas jovens comestíveis com sabor suave e versátil.',
                'maleficios'     => 'Consumo excessivo pode causar irritação no estômago. Algumas pessoas com alergia a Asteraceae podem reagir.',
                'curiosidades'   => 'Considerada erva daninha em muitos países, mas valorizada na medicina tradicional chinesa. Funciona bem como planta companheira em hortas.',
            ],
            // ── Plantas originais do catálogo ────────────────────────────────
            [
                'nome_popular'   => 'Jiboia',
                'nome_cientifico'=> 'Epipremnum pinnatum',
                'familia'        => 'Araceae',
                'genero'         => 'Epipremnum',
                'especie'        => 'E. pinnatum',
                'origem'         => 'Sudeste da Ásia',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 200,
                'toxica_pets'    => true,
                'epoca_poda'     => ['primavera', 'verão'],
                'beneficios'     => 'Cresce rápido e vicia fácil. Ótima para pendurar ou trepar em suportes. Purifica o ar de compostos orgânicos voláteis.',
                'maleficios'     => 'Tóxica para pets: oxalato de cálcio pode causar irritação na boca e no trato digestivo de cães e gatos.',
                'curiosidades'   => 'Pode crescer em água indefinidamente. Uma das plantas mais recomendadas para iniciantes por sua extrema resiliência.',
            ],
            [
                'nome_popular'   => 'Peperômia',
                'nome_cientifico'=> 'Peperomia obtusifolia',
                'familia'        => 'Piperaceae',
                'genero'         => 'Peperomia',
                'especie'        => 'P. obtusifolia',
                'origem'         => 'América Central e do Sul',
                'habitat_luz'    => 'meia_sombra',
                'porte_max_cm'   => 30,
                'toxica_pets'    => false,
                'epoca_poda'     => ['primavera'],
                'beneficios'     => 'Planta compacta e de baixa manutenção. Folhas carnudas e brilhantes. Ótima para estantes e ambientes com luz indireta.',
                'maleficios'     => 'Segura para pets. Sem toxicidade conhecida para humanos ou animais.',
                'curiosidades'   => 'Folhas carnudas armazenam água, o que a torna resistente ao esquecimento de rega. Cresce muito lentamente.',
            ],
        ];

        foreach ($plants as $plant) {
            $plant['slug'] = Str::slug($plant['nome_popular']);
            Plant::updateOrCreate(
                ['nome_cientifico' => $plant['nome_cientifico']],
                $plant
            );
        }
    }
}
